version: '3.4'

services:
  postgres:
    container_name: threads_db
    image: postgres
    ports:
      - 5432:5432 # Add a space here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads # Change POSTGRES_DATA to POSTGRES_DB
      POSTGRES_PASSWORD: threads

volumes:
  postgres_data:

